# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy on GitHub pages

on: workflow_dispatch
#  # Continuous delivery
#  push:
#  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install dependencies
        run: yarn ci

      - name: Test project
        run: yarn test --if-present

      - name: Update git config and state
        run: |
          git config user.email "julien.de.conti@gmail.com"
          git config user.name "Julien De Conti"
          git remote set-url origin https://x-access-token:${{secrets.ACCESS_TOKEN}}@github.com/smourph/palm-island.git
          git config --local --list
          git fetch --all

      - name: Deploy with with gh-pages
        run: yarn run deploy
